
/**
 * @file		L01.c
 * @author		yami
 * @date		2015-04-26 14:02:24
 * @brief
 * 这是第一关的所有文本
 */

//序章第一段
[0x0813]	=	"Over a millennium ago,"
		"\x01"
		"humans and dragons lived"
		"\x01"
		"together on a peaceful and"
		"\x01"
		"luscious land called Blaine."
		"\x03\x01"
		"However, the dragons feared"
		"\x01"
		"the progression of humans in"
		"\x01"
		"both technology and quantity."
		"\x03\x01"
		"So began the war that would"
		"\x01"
		"result in the death of dragons"
		"\x01"
		"and humans alike..."
		"\x03\x01"
		"But ultimately, dragons overcame"
		"\x01"
		"the humans, and mankind was"
		"\x01"
		"forced to make a decision."
		"\x03\x01"
		"Seven leaders of the war,"
		"\x01"
		"known as valiant warriors"
		"\x01"
		"from all across Blaine,"
		"\x03\x01"
		"decided that at the very least,"
		"\x01"
		"the existence of humanity must"
		"\x01"
		"be preserved, no matter the cost."
		"\x03",


//第二段
[0x0814]	=
		"\"All that is living"
		"\x01and all that is animate"
		"\x01is made up of the energy"
		"\x01known to man as ether.\""
		"\x03\x01Knowing this, the hero Magus"
		"\x01used his ability to control"
		"\x01the flow of ether around him"
		"\x01to save many lives."
		"\x03\x01Nobility and their servants"
		"\x01gathered together, and Magus"
		"\x01used the ether of the humans"
		"\x01and dragons who had died\x03"
		"\x01to warp away to a new continent,"
		"\x01far away from the Dragons,"
		"\x01where the chosen humans who"
		"\x01lived could start anew."
		"\x03\x01And so, in order to save the"
		"\x01lives of a few, the lives of"
		"\x01many more were sacrificed.\x03",

//第三段
[0x0815]	=	"This new land, named Solum\x01"
		"by the hero Arbiter,\x01"
		"was not nearly as bountiful\x01"
		"as their homeland of Blaine.\x03\x01"
		"But the people endured,\x01"
		"and their paths separated.\x03\x01"
		"Arbiter, who was the leader\x01"
		"of all humans, made a nation\x01"
		"based on the principles of\x01"
		"justice and freedom.\x03\x01"
		"His nation, named Blaine in\x01"
		"honor of the old land,\x01"
		"would one day tame the\x01"
		"beast known as the Wyvern\x03\x01"
		"and fly them across the continent\x01"
		"to see the new lands below\x01"
		"from the sky high above.\x03\x01"
		"The gifted mage Magus traveled\x01"
		"in the opposite direction,\x01"
		"forming a powerful military\x01"
		"nation to the northwest.\x03\x01"
		"He would call this\x01enormous stretch of land\x01"
		"\"the New Magus\", which\x01"
		"was later renamed Magnus.\x03",

//第四段
[0x0816]	=	"To the North, Queen Chelia\x01"
		"decided that she would live\x01"
		"a life in a peaceful area\x01"
		"blanketed by white snow.\x03\x01"
		"This beautiful land would be\x01"
		"named by Chelia herself to be\x01"
		"\"the Country in the Snow, Alicia\".\x03\x01"
		"Southeast, but above Blaine,\x01"
		"Korra formed a large family of\x01"
		"people who wanted to live simple\x01"
		"lives of peace and tradition.\x03\x01"
		"He called the plains they\x01"
		"settled on \"Atheya\".\x03\x01"
		"South of Magnus and\x01west of Blaine,"
		"\x01Duke Forcystus strived to make\x01"
		"a nation of equality as well.\x03\x01"
		"He built from the east to\x01"
		"the west, and treated the\x01"
		"people he entrusted with his\x01"
		"cities with love and care.\x03\x01"
		"This land, known as Valencia,\x01"
		"was meant to be one where\x01"
		"its people lived happily\x01"
		"and in eternal prosperity.\x03",

//5
[0x0817]	=
		"But for those who did not\x01"
		"believe in the constraints\x01"
		"of government, they followed\x01"
		"the old and wise Jazen.\x03\x01"
		"He moved even further west\x01"
		"onto an archipelago where\x01"
		"people were meant to live\x01"
		"isolated and quiet lives.\x03\x01"
		"However, Jazen soon passed away,\x01"
		"and this mineral-rich land\x01"
		"became one of conflict between\x01"
		"those who wanted its bounty.\x03\x01"
		"The seventh hero, Yulia,\x01"
		"was the only one who remained\x01"
		"back on the original Blaine.\x03\x01"
		"Sympathetic and unwilling to\x01"
		"sacrifice her people,\x03\x01"
		"Yulia stayed behind to\x01"
		"care for those who were not\x01"
		"chosen to move on to Solum.\x03\x01"
		"Her and the other people's\x01"
		"sacrifice became legendary,\x01"
		"and Forcystus later erected\x01"
		"a city to honor her name.\x03",

//6
[0x0BE3]	=	"But this war, \"The Falling\",\x01"
		"would not be the last.\x03\x01"
		"Magnus would grow into an\x01"
		"empire of unparalleled\x01"
		"strength, due to the descendents\x01"
		"of its creator, Magus.\x03\x01"
		"Skilled with magic and\x01"
		"prosperous like no other,\x01"
		"the Empire of Magnus began\x01"
		"a long and vicious war.\x03\x01"
		"It quickly overwhelmed Alicia\x01"
		"to the North, and instigated\x01"
		"a series of internal conflicts\x01"
		"between the tribes of Atheya.\x03\x01"
		"Being the closest to the\x01"
		"Western Archipelago, Magnus\x01"
		"monopolized its resources, and\x01"
		"Valencia would be next to fall...\x03",


//开场对话
[0x0A69]	=
		"\x09\x10O\x01\x01\x0C\x10\x83\x01\x01"
		"Duke Paul of Aegis.\x01"
		"Long has it been...\x03\x01\x09\x01"
		"Tch...\x03\x01\x0C\x01"
		"Don't look so sour, Duke.\x03\x01"
		"After all, I'll be sparing\x01"
		"the citizens of Aegis.\x03\x01"
		"You should be thanking me\x01"
		"for my graciousness.\x03\x01"
		"\x09\x01"
		"Graciousness?\x03\x01"
		"There is nothing gracious\x01"
		"about what you've done...\x03\x01"
		"\x0C\x01"
		"Hahahaha...\x01"
		"A sore loser, aren't you?\x03\x01"
		"I would be too, if my castle were\x01"
		"conquered as quickly as yours.\x03\x01"
		"The other territories of Valencia\x01"
		"have already surrendered to me...\x03\x01"
		"And the people who might\x01"
		"have actually helped you\x03\x01"
		"didn't live long enough to\x01"
		"get that chance, did they?\x03\x01"
		"Seems like nothing will go\x01"
		"your way, will it, Duke Paul?\x03\x01"
		"\x09\x01\x16"
		"......\x16\x01"
		"...It's true, isn't it?\x03\x01"
		"You warped your armies here.\x03\x01"
		"\x0C\x01"
		"I did not.\x01"
		"This kid next to me did.\x03\x01"
		"He is the most talented\x01"
		"mage on all of Solum.\x03\x01"
		"He is my trump card,\x01"
		"and my most prized possession.\x03\x01"
		"\x09\x01"
		"Him?\x01"
		"But that's... absurd..."
		"\x03\x01"
		"\x0C\x01"
		"Believe what you will.\x03\x01"
		"You will have time to think\x01"
		"about it, in a dungeon.\x03\x01"
		"Just stay there and wait... wait for\x01"
		"me to restore peace back to Solum."
		"\x03\x11\x01\x09\x01"
		"Restore peace?\x01"
		"You started this war!"
		"\x03\x01"
		"How can you even spout the word \"peace\"\x01"
		"after all the people you've killed?\x03\x01"
		"Emperor Louis!\x01"
		"Answer me!\x03\x01"
		"\x0C\x10\x83\x01\x01"
		"...Even if I told you,\x01"
		"it wouldn't make a difference.\x03\x01"
		"You're too concerned with the well-being\x01"
		"of your people to understand my actions.\x03\x01"
		"Now, I must bid you farewell, Duke.\x01"
		"May you see the light someday."
		"\x03",

//第一章地图对话
[0x0818]	=
		"\x09\x10\x88\x01\x0C\x10\xA6\x01\x01"
		"Sir Byron!\x03\x01"
		"This is the place!\x03\x01"
		"This village is hidden,\x01"
		"but there's nowhere to run.\x03\x01\x09\x01"
		"That is good.\x03\x01"
		"After chasing him around for so long,\x01"
		"I couldn't stand him just slipping by us.\x03\x01"
		"The troubles we go through to ensure\x01"
		"Magnus's lasting dominance...\x03\x01"
		"Alright, men!\x01"
		"You have the order!\x03\x01"
		"Subdue the Valencian Scum!\x01"
		"We must not let this drag on!\x03\x01"
		"For glory! Honor!\x01"
		"The Empire!\x03",

//主角对话
[0x0819]	=
		"\x0C\x10\x16\x01\x09\x100\x01"
		"Father, bad news!\x1F\x01"
		"Some Magnian soldiers are here!\x03\x01"
		"\x0C\x01"
		"What?\x01"
		"What could they want...?\x03\x01"
		"Shon, could you see\x01"
		"how many there are?\x03\x01\x09\x01"
		"There are only a few, and\x01"
		"they don't look very strong...\x03\x01\x0C\x01"
		"I can't imagine they would send\x01"
		"anything but a scouting force...\x03\x01"
		"Well, it looks like we're\x01"
		"going to have to leave.\x03\x01\x09\x01"
		"What?\x01Right now?\x03\x01\x0C\x01"
		"These soldiers can only\x01"
		"be after me, Shon.\x03\x01"
		"If I stay here, I'll be\x01"
		"endangering the villagers.\x03\x01\x09\x01"
		"O-okay...\x01"
		"I'm coming too!\x03\x01\x0C\x01"
		"Fair enough, Shon.\x03\x01"
		"You've trained enough to\x01"
		"fight their grunts,\x03\x01"
		"but stay back and leave\x01"
		"the leader to me.\x03\x01"
		"Use your head or lose your head.\x01"
		"Don't do anything reckless.\x03\x01"
		"If you don't want me to\x01"
		"repeat these same sayings\x03\x01"
		"over and over again, then\x01"
		"show me I don't need to, okay?\x03\x01\x09\x01"
		"Understood, Father.\x03\x01\x0C\x01"
		"Hmph.\x01"
		"Alright then...\x03\x01"
		"Why don't we greet our guests?\x03",

//出到地图的对话
[0x081A]	=
		"\x0C\x100\x01\x09\x10\x16\x01\x01"
		"It's time for battle, son.\x03\x01"
		"Things can get rough, so take it\x01"
		"seriously and watch your back.\x03\x01"
		"If you feel threatened,\x01"
		"move behind me.\x03\x01\x0C\x01"
		"I'm not a kid anymore, Father.\x01"
		"I can handle myself.\x03\x01\x09\x01"
		"Well, this is your\x01"
		"first real fight.\x03\x01"
		"Even if you're not a kid,\x01"
		"you're not an adult.\x03\x01"
		"I'll protect you,\x01"
		"so just stay close.\x03\x01\x0C\x01"
		"Father...\x01"
		"Alright.\x03\x01\x09\x01"
		"And now, our battle against\x01"
		"these dastard Magnians!\x03",

//敌boss
[0x0BE4]	=
		"\x0C\x10\x88\x01\x01"
		"Oh, so he's noticed us\x01"
		"and come out to play, huh?\x03\x01"
		"Boys, I hear the guy we're\x01"
		"facing can't even fight normally.\x03\x01"
		"Something about an accident where\x01"
		"he suffered some injury...\x03\x01"
		"Whatever the case,\x01"
		"he's no match for us!\x03\x01"
		"Move out and finish\x01"
		"this quickly, boys!\x03\x01"
		"And kill any accomplices,\x01"
		"no questions asked!\x03",



//战斗开始

//Siegfried遇到敌人时对话
[0x0826]	=
		"\x0B\x10\x16\x01\x01"
		"So, you've come to\x01"
		"hunt me down at last...\x03\x01"
		"Please, do you honestly think\x01"
		"you can best me in battle?\x03",

//boss对话
[0x0831]	=
		"\x10\x88\x01\x01"
		"...Amongst my comrades,\x01"
		"they call me Byron...\x03\x01"
		"Amongst my enemies, I am\x01"
		"called Byron the Lion!\x03\x01",


//杀死boss的对话
[0x0832] = ""
		   "...Knight, you will..."
		   "Regret this..."
		   "",


